### ISSUE TITLE
Composer - Dependency Manager for PHP

### ISSUE THREAD

**Issue by sandrokeil** [php-usergroup-dresden/talks#2]
- Was ist Composer
- Einbindung in das Projekt
- Composer Konfiguration
- Command-Line-Interface
- Composer Schema
- Best practices

@hollodotme Dies könnte ein guter Eintieg für #1 sein, Je nach dem ob die Teilnehmer Composer schon kennen oder nicht.

**Comment by hollodotme** [comment]
:+1:  Ausgezeichnete Idee.

**Comment by nekomajin** [comment]
:+1:

**Comment by FrankGiesecke** [comment]
Für einen Teil der Punkte habe ich in Chemnitz schon einmal einen Talk vorbereitet und gehalten.
Wenn ihr wollt, würde ich das gern in DD noch einmal tun.
