### ISSUE TITLE
Symfony Flex in Action

### ISSUE THREAD

**Issue by chr-hertel** [php-usergroup-dresden/talks#23]
**Abstract**

Symfony Flex is a revolution in the world of Symfony and changes the way of building applications. A developer needs to focus more on dependencies, but can easily increase productivity and lower the footprint of an application. We accompanied Symfony on the way to the new Flex era and will give you concrete examples how application development now looks like and explain the key concepts.

**Speaker**
- Christian Flothmann ([@xabbuh](https://twitter.com/xabbuh)) - Developer at SensioLabs and Symfony Documentation and Core Team member
- Christopher Hertel ([@el_stoffel](https://twitter.com/el_stoffel)) - Developer at SensioLabs and Organizer Symfony User Group Berlin

**Slides**
https://speakerdeck.com/el_stoffel/symfony-flex-in-action

- The talks was hold at [SymfonyLive Berlin 2017](https://joind.in/event/symfonylive-berlin-2017/symfony-flex-in-action)
- Duration ~45 min

**Comment by chr-hertel** [comment]
ping @xabbuh btw 😄

**Comment by hollodotme** [comment]
Event is announced on:
* [Meetup.com](https://www.meetup.com/PHP-USERGROUP-DRESDEN/events/244942028/)
* [Our website](http://phpug-dresden.org/events.html#next-event)
* [joind.in](https://joind.in/talk/fce28) - Please claim your talk for feedback.
* [In the google calendar](https://calendar.google.com/calendar/embed?src=phpugdd%40gmail.com&ctz=Europe/Berlin)

**Comment by hollodotme** [comment]
Thanks again @xabbug and @chr-hertel for the great talk! Hope to see you again soon!
