### ISSUE TITLE
Mixed Realities for Web

### ISSUE THREAD

**Issue by casarock** [php-usergroup-dresden/talks#26]
## Talk description
Ok, let’s get real: VR in a Web Browser isn’t something new! 2017 Firefox rolled out their support for everyone. HTC Vive, Oculus Rift and other Hardware is being supported. You can create VR experiences using your Browser and Javascript. New browser engines are powerful enough to be able to serve the experiences on a open and standardised platform. But what about AR? Or Mixed Realities? Join my session and learn how AR or better said MR is getting into your browsers, too. See how and what the platform is being able to offer and what you could expect in near future.

## Talk length (in Minutes)

- [ ] Lightning talk (20-30 Minutes)
- [x] Main talk (45-60 Minutes)

## Preferred language
Whatever you want!

- [x] German
- [x] English

## Preferred date/time

- not before April

## Speaker names
(Please name all speakers giving this talk.)

- Carsten Sandtner

## Speakers info
(Optional, your company, your position, etc.)

- Carsten works as Technical Director in Germany. Working since 1998 in and for the open web as a developer and manager. Loving and supporting the open web and open standards to ensure that everyone can have the best possible experience with web-pages. Part of the Mozilla Reps team and a Mozilla Tech Speaker.

## Twitter handle(s)
(Optional, we usually announce speakers via https://twitter.com/phpugdd)

- https://twitter.com/casarock

## Other links
(Optional, Blog, github, medium, facebook, etc.)

- https://casa-rock.de

**Comment by hollodotme** [comment]
@casarock Thank you so much for submitting your talk. Sounds very interesting! I will get back to you as soon as we have a proposal for a meetup date. Plannings for 2018 are still ongoing.

**Comment by hollodotme** [comment]
@casarock Our events for 2018 are scheduled now. You can find them here: http://phpug-dresden.org/events.html#calendar

I would suggest the meetup on May 28, 2018 (Monday). Would that be a fit?

**Comment by casarock** [comment]
That's ok. What Time?

**Comment by hollodotme** [comment]
@casarock Great! We usually start with the main talk at 19:30 (07:30pm). Then you have 45-60 Minutes incl. Q/A.

**Comment by hollodotme** [comment]
Thanks again for the great and inspiring talk!
