### ISSUE TITLE
Automation with Ansible

### ISSUE THREAD

**Issue by susgo** [php-usergroup-dresden/talks#27]
## Talk description
Automatisierung? ANSIBLE - Einfach. Sicher. Zuverlässig.

Ansible ist ein Open-Source Werkzeug zur Automatisierung von Deployment-, Konfigurations- und Administrationsprozessen. Die Beschreibung der Aufgaben basiert auf YAML und Jinja Templates. Es lässt sich zudem in Verbindung mit Vagrant und Docker nutzen.

## Talk length (in Minutes)
- [x] Lightning talk (20-30 Minutes)
- [ ] Main talk (45-60 Minutes)

## Preferred language
- [x] German
- [ ] English

## Preferred date/time
not before February

## Speaker names
- Susann Sgorzaly

## Speakers info
(Optional, your company, your position, etc.)

**Comment by hollodotme** [comment]
Hallo Susann, vielen Dank für deinen Lightning-Talk Vorschlag!
Das Thema ist definitiv für alle interessant.

Unser nächstes Meetup nach Februar ist am Mittwoch, den 7. März.
Würde das für dich passen? Falls nicht, alle weiteren Termine für 2018 findest du hier: http://phpug-dresden.org/events.html#calendar

Ich habe noch 2 Fragen:
- Wirst du auch kurz weitere Alternativen zu Ansible erwähnen?
- Möchtest du, dass wir dich bei der Vorbereitung unterstützen, z.B. indem wir vorab eine Review von deinem Talk/deinen Slides machen? Wir bieten das generell allen Speakern an, ich habe aber gerade gesehen, dass diese Frage noch im Issue-Template fehlt. 🙄

**Comment by susgo** [comment]
Der 7. März passt. 

* Auf Alternativen werde ich wenn überhaupt nur sehr sehr kurz eingehen, da ich bisher ausschließlich mit Ansible gearbeitet habe.

* Eine Review der Slides wäre super - Danke! Bis wann braucht ihr sie?

**Comment by hollodotme** [comment]
@susgo Prima, vielen Dank. Ich werde den Lightning-Talk dann entsprechend für den 07.03.2018 eintragen. 

Eine Nennung von Alternativen ist völlig ausreichend. Es geht nur darum, dass die Leute sich mit dem Thema beschäftigen können, auch falls sie schon Erfahrung mit Ansible haben oder Ansible nicht nutzen wollen/können.

Die Slides kannst du uns jederzeit zukommen lassen zur Review, einfach an orga[at]phpug-dresden.org schicken. Ansonsten bräuchten wir mind. 3 Werktage Vorlaufzeit vor dem Meetup.

**Comment by hollodotme** [comment]
@susgo Nochmals vielen Dank für deinen tollen Vortrag! Wir freuen uns schon auf den nächsten!
