### ISSUE TITLE
Testing mit Codeception: Full-stack testing PHP framework

### ISSUE THREAD

**Issue by susgo** [php-usergroup-dresden/talks#28]
## Talk description
Codeception is a PHP testing framework for Behavior Driven Development, which covers all kinds of tests: unit tests, functional tests and acceptance tests. It is fast and simple in both usage and execution. This talk will give you a introduction to the software testing basics using codeception. It will also cover some stumbling blocks when writing tests, like:
  * Test code stability against small changes
  * Data stability
  * Test structure     

Last but not least I will give you a short outlook how to make your tests also understandable for product owners.

## Talk length (in Minutes)
- [ ] Lightning talk (20-30 Minutes)
- [x] Main talk (45-60 Minutes)

## Preferred language

- [x] German
- [ ] English

## Preferred date/time
not before february

## Speaker names
- Susann Sgorzaly

## Speakers info
(Optional, your company, your position, etc.)

## Twitter handle(s)
(Optional, we usually announce speakers via https://twitter.com/phpugdd)

## Other links

* Slides: https://www.slideshare.net/SusannSgorzaly/testing-mit-codeception-fullstack-testing-php-framework

**Comment by hollodotme** [comment]
Hallo Susann, vielen Dank für deinen Talk Vorschlag!
Testing ist immer ein präsentes und interessantes Thema und ich wäre sehr gespannt was sich bei codeception so getan hat. 

Als Termine würde ich entweder den 07. März oder den 19. April vorschlagen. (Je nachdem wann du deinen Lightning-Talk halten möchtest.) 😄 
Würde das für dich passen? Falls nicht, alle weiteren Termine für 2018 findest du hier: http://phpug-dresden.org/events.html#calendar

Ich habe noch 2 Fragen:
- Kannst du bitte noch eine kurze Beschreibung zum Inhalt des Talks geben. Interessant wäre aus meiner Sicht dabei in welchem Kontext du das Testing-Framework vorstellen möchtest: Eher das Framework an sich mit seinen Features oder an einem konkreten Projekt mit spezifischen Test-Anforderungen und wie du es dann umgesetzt hast. 
- Möchtest du, dass wir dich bei der Vorbereitung unterstützen, z.B. indem wir vorab eine Review von deinem Talk/deinen Slides machen? Wir bieten das generell allen Speakern an, ich habe aber gerade gesehen, dass diese Frage noch im Issue-Template fehlt. 🙄

**Comment by susgo** [comment]
Hier würde ich den 19. April nehmen, damit ich Erfahrungen aus meinem ersten Talk einfliessen lassen kann 😁

* Genauere Beschreibung ergänze ich im Januar.
* Eine Review der Slides wäre auch hier super - danke! Bis wann braucht ihr sie?

**Comment by hollodotme** [comment]
@susgo Prima, vielen Dank! Ich werde den Talk dann für den 19.04.2018 eintragen.

Die Slides kannst du uns jederzeit schicken zur Review. Einfach an orga[at]phpug-dresden.org.
Ansonsten bräuchten wir vor dem Meetup mind. 3 Werktage Vorlaufzeit.

**Comment by hollodotme** [comment]
Nochmals vielen Dank, dass du deinen Talk nachgeholt hast. War super!
