### ISSUE TITLE
prooph event store in action

### ISSUE THREAD

**Issue by codeliner** [php-usergroup-dresden/talks#29]
## Talk description
Domain Events als "single source of truth" nutzen, das ist eine der Kernideen von Event Sourcing. Die Grundlage dafür bildet ein Event Store. Mit dem prooph/event-store können PHP Entwickler ihre MySql, MariaDB oder Postgres Datenbank in einen Event Store verwandeln und erhalten Zugriff auf professionelle Tools zur Arbeit mit Domain Events. Der Talk gibt einen Überblick über die Funktionsweisen des prooph/event-store und zeigt welche Vorteile sich daraus für die Software ergeben.

## Talk length (in Minutes)

- [ ] Lightning talk (20-30 Minutes)
- [x] Main talk (45-60 Minutes)

## Preferred language

- [x] German
- [ ] English

## Talk preparation

Do you need support on preparing your talk by e.g. a practice session or a review of your slides? 
We are happy to help!

- [ ] Yes, ...
- [x] No, thanks.

## Preferred date/time

- 23.01.2018

## Speaker names
(Please name all speakers giving this talk.)

- Alexander Miertsch

## Speakers info
(Optional, your company, your position, etc.)

Alexander Miertsch entwickelt seit 10 Jahren Anwendungen mit PHP und JavaScript. Er ist Gründer und CEO der prooph software GmbH und unterstützt zusammen mit seinem Team Kunden in der Entwicklung von Geschäftsanwendungen, die Domain-Driven Design und verteilte Architekturen erfordern. Alexander teilt sein Wissen gerne auch in der Open Source Community und ist seit 5 Jahren einer der Core Contributor der prooph components - einer CQRS und Event Sourcing Toolbox für PHP Anwendungen.

## Twitter handle(s)
(Optional, we usually announce speakers via https://twitter.com/phpugdd)

- https://twitter.com/prooph_software

## Other links
(Optional, Blog, github, medium, facebook, etc.)

- http://prooph-software.de/
- http://getprooph.org/

**Comment by hollodotme** [comment]
@codeliner Vielen Dank für die Infos. Werde den Talk dann entsprechend überall für den 23.01.2018 eintragen.

**Comment by hollodotme** [comment]
Nochmal vielen Dank für den super Talk und die Diskussion! Du bist jederzeit wieder herzlich Willkommen!
