### ISSUE TITLE
No loops needed - Functional programming in PHP

### ISSUE THREAD

**Issue by TheAlexLichter** [php-usergroup-dresden/talks#30]
## Talk description

Funktionales Programmieren wird auch in nicht-funktionalen Sprachen immer beliebter.
Nachdem selbst Java funktionale Paradigmen in Form von Lambda-Ausdrücken implementiert hat, steht dem Aufstieg nichts mehr im Weg!
Wie das ganze in PHP aussieht, welche Gemeinsamkeiten es mit Lego gibt und warum Schleifen durch funktionales Programmieren (fast) obsolet werden, erfahrt Ihr in diesem Lightning Talk.

## Talk length (in Minutes)

- [x] Lightning talk (20-30 Minutes)
- [ ] Main talk (45-60 Minutes)

## Preferred language

- [x] German
- [x] English

(As you wish/as it is "needed". Slides will be in English anyway :relaxed:)

## Talk preparation

Do you need support on preparing your talk by e.g. a practice session or a review of your slides? 
We are happy to help!

- [x] Why not, a slide review will be useful!
- [] No, thanks.

## Preferred date/time

- Before autumn :ok_hand: 

## Speaker names

-  Alexander Lichter

## Speakers info

- Founder of Developmint

## Twitter handle(s)

- https://twitter.com/TheAlexLichter

## Other links

- https://lichter.io
- https://github.com/manniL

**Comment by hollodotme** [comment]
@manniL Danke für dein Proposal. Wie klingt der 28. Mai für dich als Termin?

**Comment by manniL** [comment]
@hollodotme Das würde passen! :relaxed:

**Comment by hollodotme** [comment]
@manniL Perfekt, dann logge ich das mal so ein! 

Für das Review deiner Slides bitte einfach eine Mail an orga[at]phpug-dresden.org schicken, sobald du sie fertig hast. Eine Vorlaufzeit von mind. 1 Woche vor dem Meetup wäre prima.

**Comment by manniL** [comment]
@hollodotme  Alles klar, danke dir :ok_hand:
