### ISSUE TITLE
Static Code Analysis in PHP

### ISSUE THREAD

**Issue by bcremer** [php-usergroup-dresden/talks#31]
## Talk description
The type system and static code analysis can help us find bugs in our code in a early phase without writing explicit tests.
I'll show you the requirements for your code to get the most of static analysis as well as the tools to get you started.

## Talk length (in Minutes)

- [ ] Lightning talk (20-30 Minutes)
- [X] Main talk (45-60 Minutes)

## Preferred language

- [X] German
- [X] English

## Talk preparation

Do you need support on preparing your talk by e.g. a practice session or a review of your slides? 
We are happy to help!

- [ ] Yes, ...
- [X] No, thanks.

## Preferred date/time
- 2018-11-12

## Speaker names
- Benjamin Cremer

## Speakers info
Web craftsman and open source enthusiast. I do web and linux stuff. Organizer of the PHP Usergroup Münster. Lead Developer at CHECK24 Münster. Former Shopware evangelist.

## Twitter handle(s)
- https://twitter.com/benjamincremer

## Other links
(Optional, Blog, github, medium, facebook, etc.)

- https://...

**Comment by bcremer** [comment]
Thanks again for having me :)

Slides are here: file:///home/bcremer/BTSync/talks/phpugdd_sca/index.html#/

This "issue" is "fixed".

**Comment by hollodotme** [comment]
It was a big pleasure, @bcremer! Thank you for joining us, the great talk and the awesome gift! 👍
