### ISSUE TITLE
GitLab Pipeline mit Codeception

### ISSUE THREAD

**Issue by nevercodealone** [php-usergroup-dresden/talks#32]
## Talk description
Wir schauen uns die unterschiedlichen Testarten von Never Code Alone mit dem Codeception Framework an. API, Unit und Acceptance Tests. Ich erstelle neue Tests direkt Live in der Session und gehe auf die Vor- und Nachteile ein. Das ganze Pushen wir dann live zu GitLab und schauen uns einen Review Workflow an.

## Talk length (in Minutes)

- [ ] Lightning talk (20-30 Minutes)
- [x] Main talk (45-60 Minutes)

## Preferred language

- [x] German
- [ ] English

## Talk preparation

Alles gut brauche nur Internet und Beamer

- [ ] Yes, ...
- [x] No, thanks.

## Preferred date/time

- 2018-12-17

## Speaker names

- Roland Golla

## Speakers info

- Initiator Never Code Alone und PHP Trainer mit dem Schwerpunkt Testing und Refactoring

## Twitter handle(s)
(Optional, we usually announce speakers via https://twitter.com/phpugdd)

https://twitter.com/nevercodealone

## Other links
(Optional, Blog, github, medium, facebook, etc.)

* Blog: https://blog.nevercodealone.de/
* GitHub: https://github.com/nevercodealone/
* Facebook: https://www.facebook.com/nevercodealone/
* Instragram: https://www.instagram.com/nevercodealone/

**Comment by hollodotme** [comment]
Vielen Dank nochmal @nevercodealone für deine Session! Hat allen viel Spaß gemacht und gelernt haben wir auch wieder was! 👌
