### ISSUE TITLE
XSS PHP CSP ETC OMG WTF BBQ

### ISSUE THREAD

**Issue by spaze** [php-usergroup-dresden/talks#35]
## Talk description
How to defend against XSS in 2019 because manually calling htmlspecialchars() is so 90s. We'll talk about templating engines, XSS Filters, Content Security Policy and more.

## Talk length (in Minutes)

- [ ] Lightning talk (20-30 Minutes)
- [x] Main talk (45-60 Minutes)

## Preferred language

- [ ] German
- [x] English

## Talk preparation

Do you need support on preparing your talk by e.g. a practice session or a review of your slides? 
We are happy to help!

- [ ] Yes, ...
- [x] No, thanks.

## Preferred date/time

- Jan 14, 2019, or anytime, really

## Speaker names
(Please name all speakers giving this talk.)

- Michal Špaček (can call me Michael if you don't speak Czech :P)

## Speakers info

(Optional, your company, your position, etc.)

- Web developer, speaker, engineer. Building report-uri.com, making the web a bit more secure place. *Full disclosure: we'll talk about report-uri.com too but this won't be a marketing talk, don't worry. I was talking about it before I started working on it, and talking about it is one of the reasons why I was invited to join. Here's an [article about me joining report-uri.com](https://www.michalspacek.com/adding-features-and-deleting-code-or-how-i-joined-report-uri).*

## Twitter handle(s)
(Optional, we usually announce speakers via https://twitter.com/phpugdd)

- https://twitter.com/spazef0rze

## Other links
(Optional, Blog, github, medium, facebook, etc.)

- https://www.michalspacek.com/
- https://www.facebook.com/spaze
- https://github.com/spaze

**Comment by hollodotme** [comment]
Thank you again @spaze for coming over. The talk was very inspiring, informative, funny and eye-opening, as usual. 👍
