### ISSUE TITLE
Make Migration of Legacy Code Fun Again - from Years to Weeks

### ISSUE THREAD

**Issue by hollodotme** [php-usergroup-dresden/talks#37]
## Talk description

Make Migration of Legacy Code Fun Again - from Years to Weeks

## Talk length (in Minutes)

- [x] Lightning talk (20-30 Minutes)
- [ ] Main talk (45-60 Minutes)

## Preferred language

- [ ] German
- [x] English

## Talk preparation

Do you need support on preparing your talk by e.g. a practice session or a review of your slides? 
We are happy to help!

- [ ] Yes, ...
- [x] No, thanks.

## Preferred date/time

- 2019-02-26

## Speaker names

- Tomáš Votruba

## Speakers info

Learn faster, earn better money and work on projects that are meaningful to you.
I help programmers to unlock their inner powers, start believing in themselves and becoming 200 % productive with less wasted energy. 

## Twitter handle(s)

- https://twitter.com/votrubaT

## Other links

- https://www.tomasvotruba.cz

**Comment by TomasVotruba** [comment]
All good :+1: Do you need anything more from me?

**Comment by hollodotme** [comment]
Nope. All fine. Looking forward to see you! :-)

**Comment by TomasVotruba** [comment]
Oh, I though it's PR ;) 

Me too!

**Comment by hollodotme** [comment]
Thank you so much again for coming over, @TomasVotruba! It was great fun and a very nice tool!

**Comment by TomasVotruba** [comment]
Thanks for having me. I'll plan my trip better next time, so I can hangout with you :+1: 

Great space btw :)
