### ISSUE TITLE
Fork, Checkout, Branch, PR, WTF? - OSS Contribution in 3 minutes

### ISSUE THREAD

**Issue by mgrundkoetter** [php-usergroup-dresden/talks#39]
## Talk description
Github is a very cool platform for Open Source Software projects (OSS). Everyone can contribute with just a few clicks. There is no need to fork, branch and create a PR yourself - GitHub will do all those steps for you! All you need is a GitHub account.
I would like to show how easy this process is with just a browser, you don't even need to install git or an IDE to contribute.

## Talk length (in Minutes)

- [x] Lightning talk (20-30 Minutes)
- [ ] Main talk (45-60 Minutes)

## Preferred language

- [x] German
- [x] English

## Talk preparation

Do you need support on preparing your talk by e.g. a practice session or a review of your slides? 
We are happy to help!

- [ ] Yes, ...
- [x] No, thanks.

## Preferred date/time

- ?

## Speaker names

- Michael Grundkötter (@mgrundkoetter)

## Speakers info

- developer @ujamii

## Twitter handle(s)

- https://twitter.com/Grundi2

**Comment by hollodotme** [comment]
@mgrundkoetter Thanks again for this nice talk. I hope we'll see you again on our stage! :)
