### ISSUE TITLE
Event Sourcing am Beispiel des Neos Content Repository

### ISSUE THREAD

**Issue by skurfuerst** [php-usergroup-dresden/talks#40]
## Talk description

Wir sind momentan dabei, eine der wichtigsten Komponenten in [Neos CMS](https://www.neos.io/) mit Event Sourcing neu zu entwickeln. Ich will in diesem Talk zeigen, wie man Event Sourcing in der Praxis anwenden kann.

Zuerst wird erklärt, was Event Sourcing und CQRS ist, in welchen Kontexten es Verwendung findet und welche Vor- und Nachteile dieses architekturelle Pattern hat. Danach gibt es eine kurze Einführung in die Architektur von Neos, insbesondere des Content Repository, um die aktuellen Probleme und Schwächen der bisherigen Architektur (ohne Event Sourcing) aufzuzeigen.

Der Hauptteil des Talks ist die konkrete Demonstration von Event Sourcing am Beispiel des Neos Content Repositories; um zu demonstrieren, wie sich dieses architekturelle Pattern auf größere, langlebige Projekte auswirkt.

## Talk length (in Minutes)

- [ ] Lightning talk (20-30 Minutes)
- [x] Main talk (45-60 Minutes)

## Preferred language

I don't mind - I am happy to do the talk in English in case this is helpful to broaden the audience; or vice-versa :) 

- [x] German
- [x] English

## Talk preparation

- [ ] Yes, ...
- [x] No, thanks.

## Preferred date/time

10. April 2019

## Speaker names

Sebastian Kurfürst

## Speakers info

see https://www.neoscon.io/speakers/sebastian-kurfuerst.html

## Speaker image

https://www.neoscon.io/_Resources/Persistent/c9082cc50469e4491cc91f3092c3150f3e8cb2ac/Sebastian-Kurfuerst_300px-250x250.jpg

## Twitter handle(s)

- https://twitter.com/skurfuerst

All the best, I am very much looking forward to the talk ❤️ 
Sebastian

**Comment by hollodotme** [comment]
@skurfuerst Thank you very much for your talk proposal! We'll add the line-up next week to all places and will announce the meetup.

Looking forward to meeting you!

**Comment by hollodotme** [comment]
@skurfuerst Thanks again for this very interesting talk. I hope we'll see you again on our stage. :)

**Comment by skurfuerst** [comment]
@hollodotme very gern :)
