### ISSUE TITLE
Practical GraphQL with Symfony & Doctrine

### ISSUE THREAD

**Issue by enscope** [php-usergroup-dresden/talks#41]
## Talk description
GraphQL is an interesting way of exposing data for client applications. Allows for highly customised data transfers based on requirements of the consumer, let it be some other system or web site. Aim of this talk would be to present the basic concepts of GraphQL and show example implementation of data retrieval, data mutations and handling lists of data in Symfony Framework.

I propose lightning talk, where basic concepts are described and example code shown and demonstrated, there are possible some more in-depth topics, the question is, whether to extend it to full talk, which I am not sure, if there are enough interesting things.

## Talk length (in Minutes)

- [x] Lightning talk (20-30 Minutes)
- [ ] Main talk (45-60 Minutes)

## Preferred language

- [ ] German
- [x] English

## Talk preparation

Do you need support on preparing your talk by e.g. a practice session or a review of your slides? 
We are happy to help!

- [ ] Yes, ...
- [x] No, thanks.

## Preferred date/time

- ?

## Speaker names

- Miro Hudak

## Speakers info

- 20+ years of experience in software development (C#, PHP, Java, ObjC/Swift) for corporate and private clients

**Comment by hollodotme** [comment]
@enscope Thank you very much for your talk proposal. If it's fine for you, I'd schedule it for the next meetup on May 23, 2019. See: https://gettogether.community/events/1048/meetup-iv-2019-mutation-testing/

**Comment by enscope** [comment]
@hollodotme ok, can do.

**Comment by hollodotme** [comment]
@enscope Thanks again for this very nice talk. I hope we'll see you again on our stage. :)
