### ISSUE TITLE
Event Sourcing

### ISSUE THREAD

**Issue by ronnyhartenstein** [php-usergroup-dresden/talks#42]
## Talk description

Üblicherweise bildet man Entity-Relationship-Modelle über das Relationale Modell ab. Mit Event Sourcing gibt es aber auch noch einen anderen Ansatz. Bei Axilaris haben wir nun die ersten zwei Projekt mit diesem Ereignis getriebenen Datenmodell umgesetzt und können aus der Praxis berichten. Spoiler: wir haben bislang alles selbst implementiert.
Welche Vor- und Nachteile diese beiden Ansätze untereinander haben werde ich aufzeigen. Dabei gehe ich u.a. auf Themen wie Normalisierung, CQRS und Projektionen ein.
Tatsächlich spielt am Ende auch die Frage eine zentrale Rolle, welcher Ansatz wo passt.

## Talk length (in Minutes)

- [ ] Lightning talk (20-30 Minutes)
- [x] Main talk (45-60 Minutes)

## Preferred language

- [x] German
- [ ] English

## Talk preparation

Do you need support on preparing your talk by e.g. a practice session or a review of your slides? 
We are happy to help!

- [ ] Yes, ...
- [x] No, thanks.

## Preferred date/time

- 

## Speaker names

- Ronny Hartenstein

## Speakers info

- Axilaris GmbH
- Teamleiter Anwendungsentwicklung

## Twitter handle(s)

- https://twitter.com/rhflow_de

## Other links

- https://blog.rh-flow.de

**Comment by hollodotme** [comment]
@ronnyhartenstein Danke für den Talk-Vorschlag, wir wollen den natürlich sehen! Würde dir unser nächstes Meetup am 13. August direkt passen als Termin?

**Comment by ronnyhartenstein** [comment]
Puh, da komme ich gerade aus dem Urlaub wieder. Zum übernächsten Treffen gerne!

**Comment by hollodotme** [comment]
OK, alles klar. Dann 13. November. Wünsche einen schönen Urlaub! :)

**Comment by tommy-muehle** [comment]
@ronnyhartenstein 
Hi Ronny, ich übernehme die Orga für das nächste Treffen da es bei uns (@lovoo) stattfindet.
Bleibt es von deiner Seite aus dabei? Dann würde ich die Website entsprechend anpassen. :) 
Viele Grüße
