### ISSUE TITLE
Initiating change: An agile approach for developers

### ISSUE THREAD

**Issue by pheller24** [php-usergroup-dresden/talks#43]
## Talk description

**Initiating change: An agile approach for developers**

You notice some things are going wrong in your team.

Code-Quality suffers, Code-Reviews are not helpful, the Architecture is a plate of spaghetti distributed over the wall.

You have many ideas how to improve the situation. But how can I push the team in the right direction.

This talk is about:
- Problematic changes
- CI as a powerful tool
- Tools and behaviors that help
- Metrics and celebrating success

I will not go into the details of different tools, but will provide a suggestion on how to use:

- PsalmPHP
- Deptrac
- RectorPHP
- CI

## Talk length (in Minutes)

- [ ] Lightning talk (20-30 Minutes)
- [x] Main talk (45-60 Minutes)

## Preferred language

- [x] German
- [ ] English - is okay, too

## Talk preparation

Do you need support on preparing your talk by e.g. a practice session or a review of your slides? 
We are happy to help!

- [ ] Yes, ...
- [x] No, thanks.

## Preferred date/time

- 9.2. (time does not matter)

## Speaker names
(Please name all speakers giving this talk.)

- Patrick Heller

## Speakers info

For over a decade of professional work I gained experience by working on many projects
and with many teams:

- 10 Years of Symfony
- As a developer in tiny Agency
- On a team maintaining a self-made E-Commerce-Platform
- Lead Developer at "Peter Hahn" - at that time one of the Top 100 E-Commerce-Sites in Germany
- Now: Backend-Lead at digistore24

## Speaker image
(Optional, link to an image or attach it as a file to the issue)

## Twitter handle(s)
(Optional, we usually announce speakers via https://twitter.com/phpugdd)

- https://twitter.com/psren/
- https://connect.symfony.com/profile/psren

## Other links

NAN

**Comment by hollodotme** [comment]
Thank you @pheller24, we already announced the talk at: 
https://www.meetup.com/php-usergroup-dresden/events/291073080/

**Comment by hollodotme** [comment]
Your talk is now also announced on our website 

* https://phpug-dresden.org/

and in our google calendar

* https://phpug-dresden.org/events.html#event-calendar

We will also stream this meetup live on YouTube:

* https://youtube.com/live/WC97uy7sakk?feature=share

Looking forward to seeing you next week! ✌️

**Comment by hollodotme** [comment]
Thank you again, @pheller24!
