### ISSUE TITLE
What is Performance Driven Development and why aren't you doing it?

### ISSUE THREAD

**Issue by SecondeJK** [php-usergroup-dresden/talks#44]
## Talk description

What is Performance Driven Development and why aren't you doing it?

Mentioned: Symfony, Laravel

## Talk length (in Minutes)

- [ ] Lightning talk (20-30 Minutes)
- [x] Main talk (45-60 Minutes)

## Preferred language

- [ ] German
- [x] English

## Talk preparation

Do you need support on preparing your talk by e.g. a practice session or a review of your slides? 
We are happy to help!

- [ ] Yes, ...
- [x] No, thanks.

## Preferred date/time

- April
- May
- June

## Speaker names

- James Seconde

## Speakers info

- Senior Developer Advocate, Vonage

A trained actor with a curious background: from Theatre Studies, to Q/A, to Business Intelligence development, to full stack web development, I am the resident specialist PHP Developer Advocate at Global Cloud Communications giant Vonage. I founded Birmingham, UK's current PHP usergroup BrumPHP, as well as being on the Fusion Meetup team. I mentor, write and speak on PHP, JavaScript, DevOps, DevRel and tech culture. I pretended to be a DJ on the way.

## Speaker image

(Optional, link to an image or attach it as a file to the issue)

## Social media handle(s)

(Optional, we usually announce speakers via https://twitter.com/phpugdd)

- https://twitter.com/SecondeJ

## Other links

- https://devtheatre.net

**Comment by hollodotme** [comment]
Hi @SecondeJK, thank you for your talk proposal! 

The next available meetup date would be Thursday, May 4, 2023. (May the fourth be with you 🤓)

Would that be a good fit for you?

I assume you will join us remotely to present your talk or do you plan a trip to Germany? Both is very welcome of course!

Let me know and we can schedule and announce your talk right away.

Thanks 🙏

**Comment by SecondeJK** [comment]
Hi @hollodotme,
May 4th works for me! I'd actually be in person as Vonage would be sending me there. Plus I'll be armed with giveaways and such.

**Comment by hollodotme** [comment]
Hi @SecondeJK, that sounds awesome! 
I'll pin your talk to this meetup and will prepare the announcement & social media stuff on the coming weekend. I'll post all links here for you to share. :)

If you need any help with your commute or stay here in Dresden, just let me know. We surely can arrange the details in the weeks befor the meetup.

Looking forward to meeting you in person & to introducing you to our lovely community!

**Comment by hollodotme** [comment]
@SecondeJK Thank you so much again for showing up in Dresden and performing your great talk!
