### ISSUE TITLE
Wie kann uns AI als Devs unterstützen?

### ISSUE THREAD

**Issue by Sa-Lat** [php-usergroup-dresden/talks#45]
## Talk description

Dabei möchte ich explizit auf Github CoPilot und ChatGPT eingehen und ein paar Beispiele vorstellen. Zudem auch zusammen mit den Teilnehmenden ein paar Anfragen ausprobieren 

## Talk length (in Minutes)

- [x ] Lightning talk (20-30 Minutes)
- [ ] Main talk (45-60 Minutes)

## Preferred language

- [x ] German
- [ ] English

Englisch wäre zur Not auch möglich. 

## Talk preparation

Do you need support on preparing your talk by e.g. a practice session or a review of your slides? 
We are happy to help!

- [x ] Yes, ...

Ich würde die Präsentation schon ein Mal auf Arbeit halten. Aber ein Review wäre nicht schlecht. 

## Preferred date/time

Usergroup im März bei queo.

## Speaker names

Sascha Latzkowski
+ tba

## Speakers info

Senior Backend Dev bei queo GmbH. Spezialisierung auf Symfony und Typo3.

**Comment by hollodotme** [comment]
@Sa-Lat Wir haben deinen Talk in unser nächstes Meetup aufgenommen und announced.

* https://phpug-dresden.org
* https://www.meetup.com/de-DE/php-usergroup-dresden/events/291406389/

Wie möchtest du, dass wir die Review vorab gestalten? Wollen wir das in einem Video-Call machen? Wenn ja, dann sag mir mal welche Datum/Uhrzeit für dich gut passen.

**Comment by hollodotme** [comment]
Nochmals Danke @Sa-Lat für den tollen Talk!
