### ISSUE TITLE
SAST für PHP Applikationen - Einstieg in Security-Bewertung mittels statischer Code-Analyse

### ISSUE THREAD

**Issue by ohader** [php-usergroup-dresden/talks#46]
## Talk description

Dieser Talk liefert einen Einstieg in die Security-Bewertung mittels statischer Code-Analyse in PHP unter Verwendung des Open Source Frameworks [PsalmPHP](https://psalm.dev/) und und setzt dies in Relation mit einigen anderen proprietären Services am Markt. Anhand einfacher Beispiele werden Möglichkeiten, neue Herausforderungen, aber auch die Grenzen von SAST erklärt.

## Talk length (in Minutes)

- [ ] Lightning talk (20-30 Minutes)
- [x] Main talk (45-60 Minutes)

## Preferred language

- [x] German
- [ ] English

## Talk preparation

Do you need support on preparing your talk by e.g. a practice session or a review of your slides? 
We are happy to help!

- [ ] Yes, ...
- [x] No, thanks.

Ich versuche die Slides vor dem eigentlichen Talk bereitzustellen, ein kurzer Review zu Thema und Inhalt wäre super.

## Preferred date/time

- März 2023, prior to [TYPO3camp Mitteldeutschland, Dresden](https://typo3camp-mitteldeutschland.de/)

## Speaker names

- Oliver Hader

## Speakers info

- 50% employed by TYPO3 GmbH
- 50% freelance web engineer
- short bio at https://t3dd22.typo3.com/speakers/oliver-hader-291

## Speaker image

- via Gravatar (e.g. https://www.gravatar.com/avatar/7ab6b4516a25c07aeeff8c05ed87b413?s=300&d=mm&r=g)

## Social media handle(s)

- https://twitter.com/ohader

## Other links

- https://www.linkedin.com/in/oliverhader
- https://github.com/ohader

**Comment by hollodotme** [comment]
@ohader Vielen Dank! Wir haben deinen Talk in unser nächstes Meetup aufgenommen und announced.

* https://phpug-dresden.org
* https://www.meetup.com/de-DE/php-usergroup-dresden/events/291406389/

**Comment by hollodotme** [comment]
Thank you again for giving this great talk, @ohader!
