### ISSUE TITLE
Architekturexplizite Applikationen mit xMolecules

### ISSUE THREAD

**Issue by odrotbohm** [php-usergroup-dresden/talks#48]
### Architekturexplizite Applikationen mit xMolecules

Applikationen basieren üblicherweise auf einem Framework oder einer Entwicklungsplattform. Einige davon erlauben es, architektonische Konzepte auszudrücken. Diese jedoch direkt in Code abzubilden, bleibt meist eine Herausforderung, ebenso wie die Trennung von fachlichem Code und Applikationsframework.

xMolecules ist eine Framework-unabhängige Bibliothek, die es erlaubt, verbreitete, architektonische Konzepte direkt in Code verschiedener Programmiersprachen darzustellen, zu überprüfen, ob Regeln bezüglich der Implementierung dieser eingehalten werden und die nötige technische Integration, sowie entsprechende Dokumentation abzuleiten.

Der Vortrag gibt einen Überblick über die Java-Variante jMolecules, den grundsätzlichen Ansatz und zeigt, wie Entwickler:innen die bereitgestellten Abstraktionen mit Frameworks wie Spring, Jackson und JPA nutzen können. Darüber hinaus diskutieren wir, wie solche Ansätze in einem PHP Port der Bibliothek nutzbar gemacht werden können.

## Talk length (in Minutes)

- [ ] Lightning talk (20-30 Minutes)
- [x] Main talk (45-60 Minutes)

## Preferred language

- [x] German
- [x] English

## Talk preparation

Do you need support on preparing your talk by e.g. a practice session or a review of your slides? 
We are happy to help!

- [ ] Yes, ...
- [x] No, thanks.

## Preferred date/time

- 

## Speaker names

- Oliver Drotbohm

## Speakers info

- Oliver Drotbohm ist Teil des Spring Engineering Teams bei VMware. Seine Arbeitsschwerpunkte liegen im Bereich Softwarearchitektur, Domain-Driven Design, REST, Spring und Persistenztechnologien. Sein neues Buch „Modulithic Applications with Spring“ erscheint 2024.

## Speaker image

- https://www.dropbox.com/s/jrjg69w72mtaucn/Portrait%20neu%202000.jpg?dl=0

## Social media handle(s)

- https://twitter.com/odrotbohm
- https://chaos.social/@odrotbohm

## Other links

(Optional, Blog, github, medium, facebook, etc.)

- https://github.com/odrotbohm
- https://www.linkedin.com/in/odrotbohm/

**Comment by odrotbohm** [comment]
Ich habe das Ende des Abstracts noch einmal etwas angepasst um ein wenig mehr Kontext in Richtung PHP zu bekommen.

**Comment by hollodotme** [comment]
Danke, @odrotbohm Ich hab es auf Meetup.com und LinkedIn geändert.
Wäre super, wenn du uns auf LinkedIn noch folgen würdest, dann können wir dich beim Event auch als Speaker hinterlegen: https://www.linkedin.com/company/php-usergroup-dresden/

**Comment by hollodotme** [comment]
Vielen Dank, @odrotbohm! War ein wirklich spannendes Thema und ich bin gespannt wie es da weiter geht, nicht nur im PHP Ökosystem.
