### ISSUE TITLE
20.03. - Wie man (un)wartbaren Code schreibt // How to write (un)maintainable code

### ISSUE THREAD

**Issue by skurfuerst** [php-usergroup-dresden/talks#53]
## Talk description

Wie schreibe ich Code, der möglichst "gut" ist? Was bedeutet das überhaupt? Seit ca. 20 Jahren arbeite ich an großen Open Souce Frameworks (anfangs TYPO3, jetzt Neos und Flow) mit. In der Zeit habe ich viel Code produziert, den ich heute nie mehr so schreiben würde - und aus dem wir heute gemeinsam viel lernen können. Ich werde Prinzipien wie Erweiterbarkeit und DRY kritisch diskutieren, zeigen, welche Fehler ich beim Entwickeln von Frameworks so gemacht habe und zeige, mit welchen Prinzipien wir schrittweise unseren Code verbessern können. Das Ganze wird eine gemeinsame Reise in große Codebases. Ich freue mich drauf!

## Talk length (in Minutes)

- [ ] Lightning talk (20-30 Minutes)
- [x] Main talk (45-60 Minutes)

## Preferred language

egal, könnt ihr aussuchen.

- [x] German
- [x] English

## Talk preparation

Do you need support on preparing your talk by e.g. a practice session or a review of your slides? 
We are happy to help!

- [ ] Yes, ...
- [x] No, thanks.

## Preferred date/time

- 20.03.

## Speaker names

Sebastian Kurfürst

## Speakers info

Sebastian ist leidenschaftlicher Software-Architekt & Coach, und seit über 20 Jahren in Open Source Projekten involviert.

Nachdem er im TYPO3 Kernteam war, ist er seit über 13 Jahren mitverantwortlich für Neos CMS. Sebastian hat hier viele Teile maßgeblich mit gestaltet, u.a. die React-UI, und die Rendering-Schicht mit Fluid und Fusion.

Momentan fokussiert er sich auf einen Umbau des Neos Content Repository auf Basis von Event Sourcing.

Sebastian ist Mitgründer und Geschäftsführer von Sandstorm Media, einer Dresdner Web-Agentur mit Fokus auf nachhaltige Software. In seiner Freizeit geht er gern Klettern und verbringt Zeit mit seiner Familie.

## Speaker image

https://phpdd.org/assets/images/speakers/Sebastian-Kurfuerst.jpg

## Social media handle(s)

(Optional, we usually announce speakers via https://twitter.com/phpugdd)

- https://twitter.com/skurfuerst (nicht mehr viel genutzt leider)

## Other links

(Optional, Blog, github, medium, facebook, etc.)

- https://...

**Comment by mfuehrer82** [comment]
@skurfuerst Thanks for your talk. ❤️ 
The talk is available on our yt channel 👉  :tv https://www.youtube.com/live/YKfFaCxRtlo?si=80UxMWoM1xLAWK6f&t=4453
