### ISSUE TITLE
Livewire 3 - Modernes Frontend ohne deine PHP Komfortzone zu verlassen

### ISSUE THREAD

**Issue by pockie** [php-usergroup-dresden/talks#54]
## Talk description

Du möchtest/musst dich immer wieder mit Frontendentwicklung beschäftigen, hast aber keine richtige Lust dich dem schnellen Wandel von Frontendframeworks im JS-Bereich zu unterwerfen. Und außerdem magst du doch viel lieber Backend und PHP. Dann möchte ich dir Livewire 3 vorstellen. Entwickle effizient moderne Webapps mit wenig Javascript und viel PHP.

## Talk length (in Minutes)

- [x] Lightning talk (20-30 Minutes)
- [ ] Main talk (45-60 Minutes)

## Preferred language

- [x] German
- [ ] English

## Talk preparation

Do you need support on preparing your talk by e.g. a practice session or a review of your slides? 
We are happy to help!

- [ ] Yes, ...
- [x] No, thanks.

## Preferred date/time

- 20.03.

## Speaker names

Michael Pokladek

## Speakers info

Michael ist seit 11 Jahren im Web Development tätig und beschäftigt sich inbesondere mit PHP. Er liebt es sich in komplexe technische Details der Domäne einzuarbeiten und diese mit seinem Technologiestack für den Benutzer leicht benutzerbar zu gestalten.

Seit 10 Jahren sagt er sich immer wieder: Ich hätte mir nie vorstellen könnne, dass Terrassen so überkomplex sein können.

## Speaker image
[https://phpdd.org/assets/images/team/mpokladek.jpg](https://phpdd.org/assets/images/team/mpokladek.jpg)

## Social media handle(s)

(Optional, we usually announce speakers via https://twitter.com/phpugdd)

**Comment by hollodotme** [comment]
Thanks, @pockie!
