### ISSUE TITLE
PSR-7 / PSR-15 Middlewares

### ISSUE THREAD

**Issue by sandrokeil** [php-usergroup-dresden/talks#6]
- Was ist eine Middleware
- Wie wird diese verwendet
- Vorteile gegenüber MVC
- ...

**Comment by nekomajin** [comment]
:+1:

**Comment by tommy-muehle** [comment]
+1

**Comment by fadoe** [comment]
Ich habe mir schon Notizen zu einem ähnlichen Vortrag gemacht:
* Was ist PSR-7
* wie ist die Zusammenarbeit zwischen Libs und Frameworks ...
* Lösungen/Projekte
* Beispiele

**Comment by hollodotme** [comment]
Ich beschäftige mich gerade mit PSR-15 und bereite einen kleinen Workshop dazu vor, welchen ich gern auch der UG präsentieren möchte.
